name: Belajar Github Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sapa:
    runs-on: ubuntu-latest
    steps:
      - name: Sapa Dunia
        run: echo "Hallo github action jalan!"