name: Belajar Github Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sapa:
    runs-on: ubuntu-latest
    env:
      NAMA: "Bro"
      APP: "Belajar GitHub"
    steps:
      - name: Sapa Dunia
        run: echo "Hallo $NAMA, selamat belajar $APP!"

      - name: Cek Env
        run: echo "App yang dipelajari adalah $APP"