name: Belajar Github Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sapa:
    runs-on: ubuntu-latest
    env:
      NAMA: "Bro"
      APP: "Belajar GitHub"
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Sapa Dunia
        run: echo "Hallo $NAMA, selamat belajar $APP!"

      - name: Cek Secret
        run: echo "API Key lo adalah $API_KEY"